# Generated by Django 3.2.16 on 2022-10-27 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='accepted_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
